title               : Jalish Mahmud Sujon
description         : >-                               # >- means to ignore newlines until "url:"
                      Hello, I am a Civil Engineer. I have completed my B.Sc. in Civil Engineering in 2023. I am also a tech lover at heart and love to build websites and other cool things.

url                 : "https://jalish.alphaxb.com/"
repository          : Vucko130/vucko130.github.io 

email: jalish@alphaxb.com
github_user: Vucko130
instagram: vucko130
twitter: JalishMahmud
facebook: jalishmahmudsujon


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock